[package]
name = "netok_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
sysinfo = "0.29"
get_if_addrs = "0.5"
hostname = "0.3"
